export const FETCH_PRODUCTS_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_TYPE = 'FETCH_TYPE';
export const FETCH_ITEM='FETCH_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const SEARCH_ITEM = 'SEARCH_ITEM'